### ISSUE TITLE
Bug: Multiple hard-coded initial Admin01. 

### ISSUE THREAD

**Issue by anthony23334** [donnelldebnam/CodeU-Spring-2018-29#24]
<img width="1178" alt="screen shot 2018-05-27 at 2 39 38 am" src="https://user-images.githubusercontent.com/31927226/40583580-728cda88-6157-11e8-8415-b20e0ddcb78e.png">

**Comment by anthony23334** [comment]
Make sure that Admin01 is a "singleton" -- only one hard-coded user named Admin01 instead of having multiple versions.

**Comment by jiayiw6** [comment]
Hey Anthony, I added the Admin01 in Userstore, Admin01 should be only added once (Line 69 of UserStore); do you have any insights what caused the multiple versions? Thanks =)

**Comment by dhgarrette** [comment]
It looks like an Admin01 user gets added every time the server restarts.
