### ISSUE TITLE
MessageStore - getMessageByUser(String username)

### ISSUE THREAD

**Issue by jiayiw6** [donnelldebnam/CodeU-Spring-2018-29#26]
In MessageStore, there is the method "getMessageByUser" that takes a String parameter called "username"; this might be confusing since the field "author" in Message is actually the ID of the user instead of the username; so the parameter should be the String representation of the ID of the user instead of the username.
Let me know if I misunderstood the method, thanks! =)

**Comment by donnelldebnam** [comment]
JW, I think you may need to pull in the new changes. I’ve changes the getMessagesByUser method to take in a UUID type value and not a String. The method is working fine.
